name: Deploy
run-name: deploy site
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: ">=22.12.0"
          check-latest: true
          architecture: "x64"
      - name: install packages
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: build page
        uses: borales/actions-yarn@v4
        with:
          cmd: build
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4